### PR TITLE
Changes to make gaming experience better.

### PR DESCRIPTION
**Pull request by rrohit2901**
Made following changes in the source code to make gaming experience better:
1. Changed font style
2. Added two function to show if player is hit by mob or player shoots member of mob.
3. Changed background when new game starts after one game.

### CODE REVIEW

**Comment by rrohit2901** [comment]
n_data2
This is new gameover window.
n_data1
This is ship selection window where you can select a ship by clicking the picture.

**Comment by rrohit2901** [comment]
In last commit, basic multiplayer mode was implemented in the game.
It starts with:-
two

When we connect client then we get:-
one

After that both player get chance to select their aircraft one by one, like this:-
three
Then game starts and finally results appear:-
six
seven

**Comment by anmolharsh** [comment]
You can add an explosion animation for collision .
And add a "change spaceship" option in the game-over screen . 
By the way great-work .

**Comment by rrohit2901** [comment]
Ok...I'll soon make a commit with that...

**Comment by rrohit2901** [comment]
I added ship changing option and explosion animation in single player file. Also added buttons for all operations as ship changing was not possible without that.
new1
change
And explosion animation is:-
expl

**Comment by anmolharsh** [comment]
you may add explosion effects for collision as well .
Also, I don't know why but there are too many conflicts to be resolved for merging, please check over that as well .

**Comment by rrohit2901** [comment]
One conflict has been resolved and other two conflicts are basic designs I implemented like first conflict between line 115-125 is due to implementation of ship selection method and other one is just improvement in appearance of game ending.
Do I need to remove these to make it able to merge??

**Pull request merged**
